# Generated by Django 5.1.2 on 2024-12-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0002_otpvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpvalidation',
            name='token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
